#includepath "~/Documents/;%USERPROFILE%Documents";
#include "basiljs/bundle/basil.js";

var myStoryStrings = [
	"A long time ago, when the Gods still spoke to men in Greece, there was a merchant named Phradmus who lived in Athens. Phradmus was a much man, and had become so through his cunning and his greed. But he still wished for more is spite of his wealth, so he hatched a plot to trick Zeus into making him happy.\n\nPhradmus gathered all this wealth, and hosted a great banquet in honor of the God Zeus. a thousand cows were slain in his name. Zeus, surprised by an unexpected offering of such magnitude, came to the festival, and asked Phradmus \'Why have you hosted this great offering for me?\' And Phradmus responded to him \'O great Zeus, I am a humble man, but I have spent all my wealth on this because I have a request to make of you. I wish to be perfectly happy for one day. In return for this I will bind myself in service to you for the rest of my life thereafter.\' \n\nZeus was taken aback at the audacity of this request, but then let out a great roaring laugh. \'Phradmus\' he said, \'You have some courage. Very well. I will honor this request. Tomorrow shall be your perfect day.\' \n\nAnd on the next day nothing went wrong for Phradmus. By the end of the day he had regained all the wealth he had lost the day before, and he went to bed with the most beautiful woman in Athens.",
	"The next day Zeus approached Phradmus and asked if his day had indeed been perfect, but Phradmus replied \'Alas, great Zeus, it was not. As the day ended I was sad, for I knew the rest of my life I would be unhappy.\' Zeus was taken aback by this, but he had made a promise to the cunning man, so he said \'very well. Tomorrow I shall ensure your happiness for the rest of your life.\'\n\nAnd on the next day nothing went wrong for Phradmus. By the end of the day he had become king of the city, and had been married to the woman he had met only yesterday.Now Zeus approached him as night fell and asked him if this day had been perfect, but again Phradmus replied \'Alas, great Zeus, it was not. As I went home for the day I was sad, for I knew the rest of my life I would die.\' Now Zeus had become suspicions of Phradmus, and said, in response \' very well. You shall not die.\' and for an Instant Phradmus was truly happy, and Zeus saw into his heart and knew this was the case.Then Zeus, having completed the request of Phradmus on the next day stripped phradmus of everything. At the end of the day the man who thought he could trick Zeus was begging in the streets when the god came to him, and said \'I have made you happy. Now, though your body may die, you will not, and you will be reborn as serve me as I see fit.\'",
 	"Once a young man was given a candle when her reached manhood and was told by the wisest one in their village that he would die when the candle went out.",
 	"A hero once pulled a hair out of his beard to give to a town that loved him. It continued to grow without him, and became so large, and so liked by the people that he became jealous of it, having lost control of the thing he created.",
 	"When Odysseus was a young man, a child was born in Ithaca who could speak to hills. As she grew, the girl spent more and more time among the hills of that land, speaking to them at length. The hills were very patient, and glad to have someone new to speak to, so they humoured the child often. As a result she grew vain, and disliking of people because they gave her less of their time than the hills did. By the time she had grown into an adult she was very clever, for she had been educated by the hills, who know a great many things, and are keepers of many wisdoms and stories often missed by men. \n\nSince the girl knew many things others did not, she decided to bring the hill\'s wisdoms to men, hoping that this would give her the respect and adulation from men that she had only ever received from hills. But the people of Ithaca did not care to listen to her, for everyone who had met her had found her dislikable, and since she had never had any time for them they now had no time for her. However the girl had become like the hills, patient, and so she continued to tell her stories.\n\nHowever, the news that this curious woman among his people had begun telling stories, Odysseus decided to summon her to his court, so that he might learn the wisdom of the hills. She arrived dirty and ragged, as she always was. The hills had never cared about her appearance, since they could not see. Though offended, Odysseus took no exception, instead inviting her to eat with him so that he may hear her stories and wisdoms. \n\nThey spoke for many weeks. Odysseus learned a great many things, and became wise as he is now known for being. He also learned of the woman\'s plight, of her desire to be known and loved among men. Odysseus, though young, was clever, and devised a plan to make the woman who was a hill back into a woman. So he told her that to be loved by men she must leave the hills, and stay in the city for a time.",
 	"I\'ve heard that the richest woman on earth lived in a castle in the endless forests of then-wild Germany. She worked as a maid to the lord. She made little money, but lived in one of the most beautiful houses in the world, with an easy job, many friends, and a family that loved her, whom she also loved back. And she had this all her life.",
 	"Once there lived a young boy who, every week, would go to buy buy food in the village for his family. Every week he would go to buy bread from the baker, and say hello to the baker, and sit in his little store, and watch the man work and talk to him a little. He liked watching the skilful baker and the baker liked having someone to talk to while he worked. When he grew older his family moved to another city, and he said goodbye to the baker with great sadness. The boy began to work in a large bakery in the city, working as an underling for the other bakers. But his time in the little bakery back home\n\nHad made him knowledgable, and he had watched the baker that he loved so work for countless hours, and the men he worked with soon realized that he had a great talent for their work. Do he backed in that large store for years, until he one day took it over. At that time he has been a grown man for some time. He had gotten married and had young children of his own. \n\nOne day word of his skill reached the ears of a lord in that city, who sent a servant to buy a loaf from the baker. When The Lord took a bite of the bread it was so excellent that he wept. He summoned the baker before him, and told the baker that his was the best bread he had ever eaten, and that he would pay him handsomely to come be his personal baker and make bread for him and all his guests. The baker replied that he would gladly give the lord first choice of all his bread if he could pay to keep his shop open for a year. The Lord immediately consented, but was also compelled to ask why\'re baker had made such a request. The baker replied that he had to travel for a while, to study and better his craft.\n\nAnd so he travelled, visiting many peoples and studying the food they made. He took six months doing so. Then he went to the city where he had been born. His memories of his home where very dear to him, and he took lodging in a Hotel close to his childhood home. The morning after his arrival he woke early, as he uses to, and went down to the little shop where he used to buy bread. The baker was still there, although now twice as old as he had been before. And the great baker from the great city sat on the stool the corner as he used to, and sat and watched the old, rundown man work in his old, rundown store, and talked to him a little. And the old man did not mind because he liked having somebody to talk to while he worked.",
	"You know the Indians say a man with no purpose was born in these hills a long time ago. He grew up listless, and when he came into his inheritance he let everything go to waste. One day, he reached a point of being so wretched that he went to the army and asked him to give him a purpose.  The colonel told the man that he could only give parts of his purpose to others. The colonel was wise enough to know that a shard of a purpose was not enough to help this poor man. So the man turned to God and, failing to find him, to a man who spoke for him. The priest told him that God had already given him enough, and the he must work to find his own purpose . The man with no purpose was too hopeless to thing that that would work, so he turned to the Devil, who was easy to find. The Devil told him that he would give him a purpose in exchange for his soul. The man gave the Devil his soul, and the devil the man who had nothing a knife and nickel, and said be my Reaper Man, and wander the world collecting my souls, and once you find me one so worthless that I would be willing to part with it for pocket change, then you can buy that one off me, and have its purpose. So the man went out with his knife and his nickel, and harvested as best he could for many years, but he never found a man so worthless that he could buy it from the Devil. One day he asked the Devil where he could find a soul so worthless. Well, said the Devil, I don\'t rightly know where they come from, but I have one in my collection that is that worthless. It is yours.",
	"There were once two brothers who hated each other from an early age. When they both grew up, they were both so obstinate that they refused to leave the house of their mother when she died, so that the other would not have it. They grew old there together in that house and when they died on the same day, thy had learned to hate other in a way that hasn\'t been heard of since \n\nMy point is, boy, that you should learn to cut your losses"
]



// {"author":"chicomathmom","subeddit":"AskReddit",:"So, I got back from having my oil changed and noticed\nthat the \'See us again\' sticker wanted me back after\n5,000 miles.  I looked at my owner\'s manual, and made\na phone call.\n\n\'Hi, I just had my car serviced at your place, and I\nhave a couple of questions.\'\n\n\'Sure!  Ask away.\'\n\n\'So, How many times do you think I will be making\ntrips under 5 miles in below freezing weather between\nnow and September?\' [I live in California, for the record.]\n\nPause.\n\n\'Well, unless you go someplace very far from here, I\'d\nguess none.\'\n\n\'OK then, If I stay in Chico, do you think the\nmajority of my driving will be on dusty or unpaved\nroads?\'\n\n\'I can\'t think of *any* unpaved roads in Chico.\'\n\n\'Yeah, me neither.  So according to my owner\'s manual,\nthose are the only conditions that the service\ninterval should be 5,000 miles; for all others, it\nshould be 7,500 miles.  Now, I can think of 3 reasons\nyou indicated that I should bring my car back after\n5,000 miles.  1) Maybe you guys are unfamiliar with\nthe manufacturer\'s suggested maintenance schedule. \nBut you  guys are professionals, so I don\'t think\nthat\'s true.  2) Maybe your guys can\'t add 7,500; nah,\nyou surely have a calculator that could do that.  So\nwhat I\'m left with is 3) maybe you thought I just\nwouldn\'t notice and would bring the car back after\nonly 2/3 the time that this oil change should be good\nfor, according to Toyota.\'\n\nSilence. Then\n\'Ma\'m, do you have any other questions?\'",	


var redditStoryStrings = [
	"I was diagnosed with adult ADHD today and am being prescribed some sort of stimulant drug.\n\nCons of ADHD:  Getting anything done, procrastinating for decades, staying up to 3 in the morning with my brain whizzing around with ideas and losing my keys once a week.  Also- making careless mistakes and forgetting stuff.\n\nPros of ADHD:  Hyper-focus on some problems to the exclusion of eating, drinking breathing.  Creativity.\n\nI\'m a computational/theoretical physicist.  I depend on hyperfocus and creativity to solve problems.  Yet I\'m so focussed on my work that I let everything else go hell and can\'t get around to paying bills, answering emails etc.\n\nWhat do you think?  Is medication a good idea?\n\n  Medication\'s kicking in now!  I can feel the chatter ebb away from my brain.  It feels like one voice instead of thirty.  It feels peaceful!\n",
	"I listen to everything. I don\'t particularly like Rap and Hip-Hop although there are a few,very few single songs I like in that genre. I also don\'t care for candy pop. I listen to very little commercial stuff or classical rock.\n\nI like music from the 1930s and 40s. Texas Swing I am fond of.\nBut I\'m from the Kansas plains so alot of that is what I heard growing up and at the time not realizing what it was.\n\nAt this particular moment I am checking out the new Porcupine Tree release, which so far is not at all what I was expecting.",
	"I felt that way a few months ago.  I had a serious breakdown and was feeling really sorry for myself, and was so sad some days I didn\'t want to move, my mind was consumed with negative thoughts, and some days I would just cry for no reason.  I felt like I wanted to die, but didn\'t want to kill myself.  I eventually got tired of feeling like shit all the time, looked up some state-sponsored counseling, and tried talking it out.  The first counselor I met up with was fresh out of college and didn\'t know what the shit she was talking about.  Went someplace else, and was lucky enough to find a dude with some experience and an office wallpapered with degrees to prove it.  It was tough at first, talking to a complete stranger, but in hindsight, that was the best part of it.  He wasn\'t one of my stupid friends or parents, he was smart and listened and helped me get to the root of what was ailing me.  The whole experience changed my life, and I hope I never get stuck in a black hole like that again.",
	"I had the weirdest dream today you guys. I was in my bedroom watching Family Guy on TV (in my dream). It was a weird episode too. Peter Griffin was in a pink bunny costume watching a pay-per-view porno on television with Lois. (The porno was about a pink bunny making love to some woman in a bath tub.)\nIt looked like a cartoon version of my bedroom, but a little different. Then afterwards in the cartoon Peter somehow ended up in his bathroom. He was in a jacuzzi in what I can only describe as a spacesuit. So Lois gets in and joins him and she sticks her hand in the arm of his suit and inflates it for him; she\'s also in a suit by the way. Then while I\'m watching (I can\'t see the TV at this point) my dad comes into my bedroom. It looks like my bedroom but the layout is different. Black Tube TV at the front and some shelf furniture at the side. Anyhow, so he comes in and lies down on the floor and starts watching with me. He tells me how the episode is about God and Abraham. I get annoyed. My mom comes in. I grumble. I get up and go to turn down the radio on the cheap looking shelf. My mom yells at me, she says she\'s listening. I say \'Fine!\' and go into the hallway and start heading downstairs. I\'m irate for having to leave. As I\'m on the stairs I point up to my mom and dad and tell them that they make me want to kill myself, that they make me want to commit suicide. Then my mom starts shouting at me again. She disappears into the back of the bedroom and goes to get a belt to beat me. Then I woke up. Note, that it was actually my dad who mostly beat me with a belt.",
	"I have a condition called Precordial Catch Syndrome. I get random sharp stabbing pains in both of my sides which last for a little while, and then fade away. I\'m actually having one right now, but it\'s dull, so I\'m ignoring it.\n\nI\'ve been to the doctor about it a few times and no one really has any idea what\'s going on, or what to do.\n\nIt\'s not technically a disability, but it is really distracting and has made me black out from pain a few times.",
	"I was raised Mormon, so I was conditioned early on that coffee was an \'evil\' smell.  (Not Mormon any more, but that aversion sticks with me...)\n\nWhen I was pregnant, my sense of smell was heightened, and the smell of coffee would make me throw up.  You know how on Saturdays they sometimes have free coffee in  grocery stores, to make your shopping experience more pleasurable?  I made a big mess more than once... (It happened so fast, I couldn\'t help it.)\n\nThe smell of perfume also made me throw up on one occasion.  (It often makes me *want* to throw up now, but  I manage to keep it in check.)\n\nI\'m sure you really wanted to hear this.  Sorry...",
	"when I get a distant whiff of skunk, it reminds me of when I lived in a 100 year old ranch house in New Mexico.  \r\ncold, clear, still winter night. so many stars it\'s unbelievable and then a slight scent of skunk, probably from miles away.  \r\nscent is an extremely strong  \r\nlotsa good memories from that time in my life.",
	"My dad found another woman (a long lost girlfriend) when he was 56 and wanted a divorce. The whole thing got rather complicated and went on for about two years with my dad moving out, then moving back in, then my mom moving out and them finally, slowly, got back together. As far as I know, they haven\'t had any problems since, I stayed the hell away from the whole thing and had nothing to do with it, either way. Not to mention, I suck at relationships, anyway, so you don\'t want to listen to any advice I give...",
	"The soft hum of the laptop as I lean my ear by the exhaust vent and a breeze of warm air flows out having cooled a piece of etched silicon through which 1 billion operations are flowing every second. There is a scent of warm plastic and metal. The laptop does not vibrate; its lid is closed as I am transporting it to another room. It conceals the quiet dignity of a gentle giant whose only external manifestation is the staid, uniform hum out of the vent. My hands touch the plastic; it is neutral. Nothing betrays the quiet inferno which tumbles underneath. I lay it down on the table and open the lid, the software asks for a password. It is mine, it will run the programs I choose and produce results full of meaning and poetry; though it humbles me with its power, there is no conceit. Its life is one of working. The fan hums.",
	"There\'s a legend, at least 10,000 years old. It tells of a man who claimed to come from the future. He was so loaded down with stuff he was carrying that it was real easy to hit him over the head with a club, from behind.\nHe was quite tasty. and some of those things he had were like flat fire-logs, from the future. They burned slowly, with leaves turning over as they did. \nWe toasted those things he had on his feet. They were crispy and good too.\nSome of them popped loudly as they burned. And some of them just wouldn\'t burn.\n ",
	"I was an altar boy for 8 years, and I could write a book about it. Highlights would include:\n\n* Dodging the advances of the pederast priest (my parents warned me \'not to stay too long with Father Mc**** after Mass\' - What were they thinking?)\n\n* Being accused by the Mosignor of stealing Communion wine, when every altar boy knoew that Father O\'***** took a bottle after every service.\n\n* Being continually threatened by the Nuns that my altar boy status would be eliminated if they wanted it to, if I didn\'t stop asking questions in class.\n\n* Father *****\'s loud farting on Sundays, after which he would turn to glare at one of the altar boys.\n\n* Nearly burning the church down with the incense burner.",
	"I went to a Catholic grade school which featured a large, church. Many upper class boys were alter boys, mostly because it got us out of classes for weddings, and funerals, the former of which being the best, because the groom would usually tip us really well to show off to his new bride.\n\nAt a particularly teary funeral (must have been a young one), I put the water bucket (for blessing the coffin) down next to me at my seat, and the very ornate, heavy, solid metal handle fell down, catching the wand handle, and somehow hurtling it about 10\', throwing water into the crowd, and clanging across the marble floor. There was a stunned silence, and then one guy cracked up laughing. Then everyone burst out laughing, almost ridiculously, and little giggling outbursts lasted the rest of the service, amid all the crying. Some people were crying while laughing. It was so bizarre.\n\nThat\'s the most fun being an alter boy ever gets, unless you sneak handfuls of Eucharists wafers to eat when you\'re in that little room in the back. \n\nAlso, the 4 priests were really nice, and never did anything bad to me, which is really saying something for them, because I was one hell of a sexy 8th grader.",
	"No matter how far we as the human race advance in scientific understanding of the universe, there will always be those who look for a force outside of the natural. They want magic and mystery, somethings that nature can\'t provide (to them, I think nature has plenty of mysteries to solve). On a less serious note, horoscopes can be a ego boost, conversation starter, or simple distraction from mundane life.",
	"I have a live grenade with the pin pulled, an open barrel of deadly acid, and an angry kitten.  You can choose which one I throw at you, and I will oblige, or you can leave the decision up to the population at large.  If you select something not in my list, I\'ll ignore your choice and let the population select something for you.  \n\nIn this scenario, would you also \'not vote at all\'?  Voting for the lesser of evils is always more reasonable than not voting at all, or voting for someone/something that has no chance of winning.",
	"I frequently encounter people, both online and offline, who seem to have no actual interest in talking *with* you. Instead, they talk *at* you. They\'re not looking for a conversational partner, they just enjoy hearing themselves speak, and they have an excuse to do it if there\'s another human present for them to bounce their words off of. But if that\'s all they\'re going to do, why do you even need the other human? Just get some kind of robot that smiles and nods at random intervals when you talk at it.",
	"If you really want spectacular fires, try the two step process. Fry the potatoes at a lower temperature (about 350F) for about 3 minutes. They will not be golden brown. This step blanches the fires, cooking them throughly but not browning them. Pull them from the pan after 3 minutes, putting them on a paper towel on a plate. Move the plate to the fridge for 5 minutes. Increase the temperature of the oil to about 450-500F. Add the fries and fry to golden brown. You will be amazed at how this two step process increases the crispiness of the fries.",
	"I\'m a nihilistic hedonist, but for me hedonism isn\'t orgies and hard drugs, it\'s comedy [improv and stand-up], women, friendship, music, and movies.  It\'s not a particularly immediate goal for me, but of course, I wish to make the world a better place for people in general, which really only affects my politics ;)\n\nI think most people are actually exactly like this, they just can\'t quite intellectually stomach the notion of their life being utterly pointless in an absolute sense.  I mean if you believe in God, it\'s much easier to handle a hard life, or the hard parts in life, because you just figure that it\'ll be made up for later.  The tragedy of it is that this all we got, and if you don\'t know that, well you\'re missing out on a lot of the most awesome things in life. And yeah, I\'m preaching to the choir.",
	"I bought a nice home, had a nice fixed mortgage, everything I wanted in a home for the next 10-20 years.  I move in and the problems start happening.  Within the first three months, I had $10,000 in repair expenses for the pool, garage, A/C, windows, etc.  I bought a home warranty which covers *some* of the costs, but they will *always* find a way to maybe cover 5% of the total.  After the first month, I realized renting is better, especially in this market.  Now, had I bought three years ago, then it would have been a smart move, but a year ago and probably for the next couple years, it is a huge mistake.",
	"I think I am an Atheist today because I hated going to church. My parents forced me to go, and to go to Sunday school, where I was to memorize Bible verses, and then play dodgeball. I loved the dodgeball, but that was about it. I think the only reason why I even liked that was because I got to bean the more religious pricks in the head.  As I got older, I continued to hate church, but I was persuaded by arguments that I later learned to be the \'Argument from design\', and the \'First Cause Argument\'. I was introduced to the Second Law of Thermodynamics in church as well, as an argument for the existence of God. I used to pray every night. But then, around the time I got to middle school, I started to think about all of the other religions. I think what really got me to think about that was South Park (only Mormons go to heaven, and heaven is full of fucking stereotypical Mormons). I began to doubt. As I began to doubt, I began to compromise my faith item by item, thinking \'Ah well I guess that is just an allegory\', or \'The Bible is a mistranslated product of imperfect men.\', until eventually, the whole rotting thing fell down. The epicurean argument was inescapable. That part scared the shit out of me. To me, the idea that there was no cosmic justice in the world, and that death is permanent, just scared the living hell out of me, but it did not change the fact that religion could not be true. Now I am at peace with the idea of thinking things out for myself.",
	"I hope:\n\nPeople will learn that just because someone is in charge it doesn\'t make them right. \n\nPeople will learn that if you want it you have to work for it, instant semi wealth is not worth it. If it seems to good to be true it probably is.\n\nPeople will learn to trust others in their own communities.\n\nPeople will finally get over race, you are who decide you are and nothing else besides that. We need to applying labels to ourselves.\n\nPeople will realize that, the marvels we have built are testament the power of man, but if we are not around to enjoy them then what was the point. \n\nPeople realize that fear is pointless. Terrorism works because the mission is to scare you into submission. We lost a long time ago because we got scared and then went shopping. \n\nPeople will learn that sometimes life can not always be a convenient thing. We have decided to burn food to make gas to be able to go and buy food. We\'ve become so ingrained in patterns and classes people would drive 10 miles to get food instead of one in order to avoid certain groups of people. we can\'t do that anymore.\n\nPeople learn to lay down the law, if you can work then should be doing it. Some of us don\'t realize that the survival of a our society depend on what people put in not what people take out. Everyone needs to contribute in the best manner they know how.\n\nPeople will learn that we can\'t destroy the environment anymore. We don\'t need more biodegradable things, we need longer lasting goods.    \n",
	"I feel like crap. I had surgery a month ago which I\'m still recovering from. I don\'t have many friends and don\'t really get along with my family. I got in trouble at work (programmer) the last week for a goof up, then I got really sick on Friday. Sunday my girlfriend and I broke up, and I\'ve been sick since and have lost quite a bit of weight.. weight that took me 4 months to gain. I\'m back to 140lbs at 5\'11... I\'m at home today but feel like crap, emotionally and physically..... and don\'t know how to cheer up.",
	"I have absolutely no desire to own anything more than I already do.  Used to be obssessed with getting the newest consoles, DVD\'s etc but one day it just stopped.  I sold pretty much all my stuff and have never wanted anything new since. I\'ve got an ancient computer, some guitars and thats about it. I\'m not religious or anything, and wouldn\'t say I\'m any more or less happy now, but I do enjoy the lack of desire to possess things.\n\nOh, and shopping just seems like an alien concept to me now.",
	"I\'ve been living the college lifestyle -- macaroni, pasta, rice for dinner during the week, occasional meal at a cheap restaurant, beer on the weekends -- for the past three or four years. I graduated and I\'ve kept living more or less the same way. I used to be all about buying new gadgets and upgrading my computer every year, but once I started having to pay for rent and food, I just kind of stopped. I had an iPod and it broke. I was upset for a while but eventually realized that I don\'t really need it. My computer broke down a few weeks ago, and I\'m probably not going to replace it until the fall. I just don\'t need it when I have internet access at work. (The only thing I really miss is my music collection)\n\nI really only want money to travel and education. (I\'m going to Germany for a month and a half on my own money this summer)",
	"My wife was a synchronized swimmer, and got some knee injures (SS is hardcore). She had her legs sawed, adjusted, and pieced back together. She has a couple screws in her right knee still-- she got them out in her left knee, because the nerves began to grow around them and every time she hit a desk or something she\'d be crying for 10 minutes. We\'re saving up $ to get the screws out of her other knee...",
	"I got hit by a car when I was ten years old and broke both my legs. Had to have 2 screws in my right knee, which also ruptured my growth plate (they broke the left growth plate too, so it didn\'t outgrow the right leg). I\'m two inches shorter than what I could been, lame!\n\nAlso I had an external fixator (metal bracket on the outside holding together 4 screws into the bone) for my left femur, which was broken in two places. This was on there for 6 months, at which point the crappy doctors decided to unscrew the screws out my leg while I was still awake - with no pain killers or anesthetic. It was as bad, if not worse, than being hit by the car in the first place.\n\nSo then a couple years later I found out this wasn\'t a common practice, but also that I had to have the same thing done with a surgery on my right knee, where they took the remaining screws out and inserted another external fixator, this time with 6 screws. Thankfully they removed that after knocking me out this time.\n\nBy the way, having those on any part of your body has to be one of the worst things in the world. They are just open wounds the whole way, and they have a high risk of getting infected and there\'s not much you can do to prevent it. They even found out that cleaning the wounds on a regular basis actually heighten their chances of getting infected.\n\nseriously, be careful guys. look both ways when crossing the street.",
	"Well if life is overrated, what is underrated?  If you have nothing to live for why bother living. There is so much to do in the world, we\'ve come so far in the thousands of years of our civilizations and diversified so many ways to work, eat, and play that it is hard to contend that one person can do everything there is to life.  If you truly think life is overrated, take a few days off, stop your normal schedule, do something you didn\'t think about doing, and see where you go from there.  Then ask again is life really overrated or have you not applied yourself enough?",
	"I sometimes think life is nasty, brutal and not-short-enough, but I suspect its my attitude that needs improving more than \'life\'.\n\nMaybe I need to stop eating what I\'m served and get into the kitchen and make something I really want?\n\nThe people that seem to get the most out of life are the ones who put the most energy and creativity into living it. That\'s not easy, but it appears to be worth the effort.",
	"I\'ve had a lot of at one with the Universe, feeling connected to every living organism moments - but like another guy said, they\'re hard to accurately describe.  So with that being said, I\'ll recant my most intense one.\n\nMe and the girlfriend decide to head over to the Botanical Gardens in the suburbs of Chicago while dosed - it\'s a nice summer day, plenty of sunshine.  We drop on the bus, and about 45 minutes later the giggles commence their attack.\n\nAfter much effort, we end up on a hillside and she lays down.  As I\'m staring down at her, still locked in the grips of the giggles, my perspective begins to deteriorate rapidly.  I feel as if I am 10, 100, 10000 feet above her; things start to blur and spiral.  My voice echoes and fades out into the distance as if I am sitting atop a truly massive precipice.\n\nAt this point, I am still connected with reality.  I still know where I am, I see her (albeit distortedly) - I still feel grounded.\n\nThis, however, changes.  There is a distant *whoosh* and my peripheral vision blacks out, leaving a black blob where a tree and path once were.  I begin to hear a droning, fading noise that seems to be playing in slow-motion.  The grass she is silhouetted against changes color from a regular green to an intense, almost neon; her yellow shirt does the same.  Her giggles fade in and out and sound like they\'ve been slowed down to one-eighth speed.\n\nShe then begins to gain weight.  More and more, until she begins to look like Buddha himself.  At this point, I cannot tell reality from this world that my mind has seemingly created for me.  She tells me that I was staring at her for at least 10 minutes until the entire thing rapidly faded and, just like that, I was back on the hillside.  This has been the only time for me on LSD where I\'ve felt that I had entered another world, unable to tell the difference between what is real and what is imagined.\n\nIt was one of the most bizzare, wonderful things that has ever happened to me.  Some day, I hope to get back there.",
	"It was 1997 or so. I was in the 5th grade. Our entire elementary school had a single internet connection - dialup. One teacher showed me how to use a browser, which was just Netscape at the time, and a search engine. This was pre-Google, so we had to use Altavista. Since it was 1997, there wasn\'t really much to find on the internet. I didn\'t even really get the point of the internet until 2003, when we got it at home for the first time.",
	"Back in 1996, Internet was a really rare luxury in Greece. And I was 14. At school I was a part of the \'computer team\' (extracur. activ. group) where we would dial over and over again, because the \'terminal\' received \'garbage\'. When we managed to get a connection, we would fool around in the web, use (MS?) Chat -the one that had that drawing feature at some time- where we\'d talk to American Greeks or Cypriots in London.\n\nI remember we got a lot of pervs trying to talk to us, because our login name was \'Jeanne D\'Arc\' (name of the school, but Jeanne was enough for someone desperate).\n\nWe once talked to a 40ish Cypriot from abroad (US or UK I think) who sent us a \'3D\' design he\'d made as an architect. This was realllly fascinating at the time. \n\nI didn\'t know porn was so easy on the internet until 2000-2001 when I got a dialup connection from my uni ( I had one before, but I guess I was too innocent ).",
	"I was a clerk in the military and there was another clerk who delighted in trying to get one up on me.\nOne day as I was finishing up at the urinal and turned around to leave, he was just entering the room. As I headed straight for the door his voice mocked me in a condescending tone with: \'MY mommy taught me to wash my hands after going for a peepee...\'\nQuick as a flash I responded: \'And MY mommy taught me not to pee on my hands!\'",
	"I was outside waiting in line behind a 20-something techie wearing an apple shirt while 3 blonde girls were all at the ATM giggling for the longest time. Finally, the kid in front of me gets restless and spews, \'what is this? girls gone wild at the ATM?\'. \n\nThe girls turn around, one places her hand on her hip, furrows her brow and responds with, \'oh yeaaaaaah, girls gone wiiiiild at the ATM\' in an attempt at sarcasm. I thought that was the end of it, but he quickly shot back, \'that wasn\'t a rebuttal, it was a reiteration,\' and so I gave him my number.\n\nI\'ve wanted to use it since but was never given the opportunity. ",
	"When I was deployed in Kabul, my interpretor, who is male, was always trying to hold my hand when we were walking. Really freaked me out and apparently all the guys over in that region do it.\n\nAlso no one says anything after someone sneezes. It\'s such a knee-jerk reaction for many people to say Bless You after someone sneezes, even an atheist like me. But in Afghanistan there isn\'t an Afghan equivalent to Bless You. It felt very strange at first not to say anything when someone did sneeze but eventually I forgot all about it. Then I came back to the states and my wife got mad at me for not acknowledging her sneeze. ",
	"I am bizarre looking to every culture.\n\nMiddle eastern people living in america are actually very pro western including Iranians.\n\nMany young and old immigrants I have talked with and seen are very strong individualists. They have to be to come across a ocean and study in a foreign land and have a extreme strive to succeed.  \n\nAfricans, and I mean people from Africa. are very nice as well and have cheery dispositions.\n\nThe American equivalents of all these groups tend to stay together. Now its not the individuals one on one but rather when people form up into racial cliques. To a degree its really a matter of cultures, everybody has nothing equal to share in terms of likes when dealing witch each others race. Whats under this is the deep underpinnings of racism which only comes out to the best of confidantes of the same race. However its not a broad sort of racism you would expect, its a very selective racism direct those whom are the most abrasive individuals.\n\nJust a few things I learned at a very diverse school.   ",
	"I\'m from the south (US) and for the most part, I am very proud of that.  When abroad people don\'t know how to take my accent.  \'Are you from the UK, Australia?\'  \'No, the US.\'  \'WHAT?!\'\n\nI\'ve noticed that I wasn\'t as uncomfortable as I thought I would be (except in Marsaille France, but it\'s sketchy).  \n\nThat over all, people are nice.  Some of the nicest reside in Switzerland.  A smile and a nod goes a really long way.\n\nFear is the same in all languages (when they take the exit door in front of you out to repair it while you\'re on a plane, and the woman beside you is spouting out in Spanish, and you don\'t speak a word, you still know what she is saying).\n\nThe biggest thing I learned, I don\'t like most American\'s either, but that\'s true even when I\'m home.",
	"I remember taking a trip somewhere when I was a kid. I distinctly remember seeing a giant sign that had all this information about trees. The one thing I remember from it was that they predicted that the rain forest would be gone by 2050, if we kept up our systematic destruction of the environment at the same rate.\n\nIn this topic, I\'m a pessimist. I don\'t think humans will be able to live beyond that time unless we do something drastic.",
	"I\'ve been to 14 countries (in North America, Europe, Asia and South America) and here are my key lessons:\r\nThe best way to avoid being treated like an idiot is to learn at least some of the language so you can ask them questions.  For the most part, a lot of people speak English, but they won\'t tell you if you don\'t try the language of the country you\'re in.\r\nAlso, if you are from the US, tell people you\'re Canadian.\r\nRelationships aren\'t as shallow overseas.  You make friends for the rest of your life, not until you get another job.  Relationships aren\'t as disposable.\r\nBrussels has a lot more to offer than I thought it would, including amazing food.\r\nAnd every time I leave the US, I realize how little I really know about the world.",
	"I\'m italian descendant (all my fathers family is from italians immigrants in Brazil), I don\'t watch TV (sorry, but Italian TV is one of the worsts I\'ve ever seen, I completely agree with Beppe Grillo that there\'s urgent need for change) and for the last two years at least I\'ve been watching Czech and Italian movies only (which was the two countries I lived in).\n\nThe \'mafia relationship\' issue was told to me **by an Italian** that was born and still lives in Milan.\n\nA friend of mine, brazilian that lives in the USA, once told me that the one of the best things from latin cultures are that people are ALWAYS complaining. The foremost is, obviusly, the government. Everywhere in Latin America, Portugal, Spain, France and Italy, people **always** complain about the government, even if things are going ok there\'s always space for improvement. Which was a complain he had with American (and Anglo-Saxon) culture, where it was almost sacred to critize your own government.",
	"when I graduated college with a b.a. I applied to a graduate program in computer art and science.  it was a competitive selection process and I didn\'t have the skills or portfolio, so I wasn\'t selected.  went to work at a bank.  12 months later I decided \'this is like slow death.  I should go back to school for a year, work on my computer skills, build up my portfolio, then reapply to the masters program.\'  I went back to school and after a semester of really focused work, which by the way was the first really focused semester I had ever spent at school, I was in the program which had previously rejected me and I felt like I could fly.  the year at the bank was invaluable, because it made it very clear to me what I did not want for my life, and motivated me to go after what I did want.  honestly, if you have no passion for life, I do seriously recommend you just get a boring job.  either it will suit you and you can just use your money to pursue hobbies outside work or you will get sick of it and feel the fire to pursue something again, and the \'something\' might seem a lot clearer at that point.  just my two cents.",
	"Sometime during elementary school our class took a trip to the Metropolitan Museum of Art.  For some reason we had to go through one of the side entrances (near the parking lot).  Before our line went in, I happened to look up towards the lot.  An overweight man was running around in his underwear, wearing tissue boxes as shoes.  I looked over to my friend and asked, \'Did you just see...?  \'Tissue boxes!\' was the response.  Unfortunately nobody else was looking in that direction at the time.  I\'ll never forget Mr. Kleenex.  ",
	"my best friend fell off a four story roof a couple years ago. I was the first one to get to him lying in a broken heap on the asphalt in the backyard. he\'s ok now, but that was probably the most surreal moment of my life.\n\nabout 5 years ago in Arcata CA, my girlfriend and I were walking home from a friends house at about 4am when we veered off to a side street to investigate a huge glow in the sky. it was an abandoned church on fire. the stained glass had all broken away and the inside was just this raging inferno all around the altar. we stayed looking at it until the steeple fell, engulfed in flame. fucking craziest shit I ever saw.",
	"Oh man, the weird things I\'ve seen in Tokyo. \n\nIn Shibuya, I saw a guy doing a headstand on the steps outside HMV records. Came back an hour later heading to a different bar, he was still there. Can\'t seem to find the pic I had of it, though.",
	"\'I\'ve seen things you people wouldn\'t believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the Tannhauser gate...\' Unfortunately I can\'t claim that to be something I saw.\n\nI did once see a guy listening to Polish Hip-Hop on a boombox, wearing a 1970s shellsuit and dancing like jay &amp; silent bob, behind my local supermarket.\n\nCome to think of it, there are several freak/uniques around my area that provide much amusement. One favourite is Running Man. At first I thought it was just me who only ever saw him running (with a very strange, over-zealous gait) everywhere - but my friends have all mentioned at one time or other having seen the same. I think he\'s a bit special.\n\nPhysically different people are always fascinating, and you feel guilty for looking but you just can\'t help it. There is a guy that works in the same office as me, he has an enlarged chest, no neck and could audition for the HunchBack of Notre Dame.\n\nI guess I am rambling, but it helps me to remember. It has in fact jogged my memory to remind me of a woman I saw recently.\n\nNow I am 6 feet 2, and she cleared me by a good few inches. Her body wasn\'t disproportionate, so she wasn\'t a beanpole. She did had extremely long arms, and she was wearing what on a normal woman would be a long dress reaching half way down their lower leg; On her it was above her knees. It just looked bizarre - But I imagine she might have trouble shopping for normal clothes.\n\nYeah, all my strange things are people, I think I am perhaps too fascinated by peoples peculiarities.\n\noh yeah, that foot with the hole on reddit recently. dear frackin\' jebus. Just wrong.",
	"My girlfriend \'J\' and I were watching the meteor shower on Aug 12 2007 on our rooftop patio in downtown San Rafael. We\'re about 20 miles north of San Francisco and it\'s a fairly urban area, so light pollution is fairly high. There was no moon, however, so we had a better view of the stars than usual.\n\nWe were stretched out on two lounge chairs, with a blanket over us. We weren\'t under the influence of any drugs, though I had finished about half a pint of Guinness. I had a mini mag light flashlight with me, and my binoculars. We weren\'t seeing many meteorites, so out of boredom I had been swinging the flashlight beam around into the sky in big sweeps.\n\nI got up to go to the bathroom, and I got a few steps away when J started yelling \'UFO! UFO!\' I started looking up and around and a couple seconds later I spotted a dark triangular shape with rounded corners moving quickly across the sky, from approximately north to south, more or less right above us. It had a small red circle in each corner, and was completely silent. I\'d estimate that it was about the size of 2 or 3 full moons. I said \'hand me the binoculars!, hand me the binoculars!\' but was too dumbstruck to look away to grab them, even though J was holding them out to me (her eyes also locked on the triangle). I watched it for about 4 or 5 seconds until it disappeared in the haze of light pollution to the south. I\'d say it traveled about 1/8 of the full arc of the sky in the 4 or 5 seconds that I was able to visually track it.",
	"Here in Japan-\n\nPassing the entrance exams can be a grueling ordeal, but College itself is a four year vacation. You can do nothing. Its not unheard of for some students to literally only attend class a couple times in four years, and still graduate with a C. The professors at some places show up for class half an hour late, 15 minutes early, and basically just talk at the class while students listen motionlessly or sleep. The profs only publish in in-house papers, and the work is garbage or plagiarized.\n\n\r\nTheyre not really \'universities\' in the universal sense of the word. Everyone is just going through the motions to make it look that way.",
	"Angry black woman: Are you sayin\' the Democratic Party don\'t care about the African-American community?\n\nBullworth: Isn\'t that OBVIOUS? You got half your kids are out of work and the other half are in jail. Do you see ANY Democrat doing anything about it? Certainly not me! So what\'re you gonna do, vote Republican? Come on! Come on, you\'re not gonna vote Republican! Let\'s call a spade a spade!\n[Loud, angry booing]\n\nBullworth: I mean - come on! You can have a Billion Man March! If you don\'t put down that malt liquor and chicken wings, and get behind someone other than a running back who stabs his wife, you\'re NEVER gonna get rid of somebody like me! ",
	"I remember meeting a post-grad Japanese student of English language at the University of Sydney. I took her out on a date one night, I spoke most of the time and thought she was just very shy. At a later moment I just realised she couldn\'t understand shit of what I was saying. Which led me to wonder how she could have obtained an undergrad degree in English.\n\nOn a sidenote, another socially unacceptable fact: Japanese girls are total sluts.",
	"I wanted to be a cosmetologist, a tattoo artist  or an elf. \n\nI am now a house-wife. I went 3/4\'s of the way through beauty school but had to drop out because I moved and didn\'t go back because there wasn\'t a school within driving distance. I\'ve given up on being a tattoo artist as the industry is flooded with apprentice hopefuls. And as far as I know becoming an elf is impossible, much to my dismay.",
	"When I was a kid I really wanted to be a garbage man. I would wait for hours on my balcony for them to show up, hook the containers to the truck and empty them, then get in the back of the truck and drive off. They were fucking awesome, wearing orange suits with those reflector strips, and riding on the outside of the truck, how cool is that.\n\nI\'m in grad school now, electrical engineering, completely miserable.",
	"I always wanted to be a nurse. Over the last 18 years I have seen more blood, vomit, pee and even poop than most people will ever see in their lives. I have seen broken bones and injuries that were only sprains, even though the patient was screaming like they were dying. I have sat by the bedside of very ill people and comforted them. I have seen countless IV\'s and dispensed any number of medications. I\'ve taken temperatures, checked blood sugars and the list could go on forever. The kicker is, I\'ve never had a nursing license of any kind and I do not get paid for my services. I am what they call a \'mom\'.",
	"A cabbie in New York posed this riddle for an Icelandic tourist. The tourist thought hard until they reached the hotel, where he gave up and asked the cabbie for the answer. The cabbie said \'Well, it\'s me of course!\'\n\nThe Icelander took the elevator to his room where his wife was waiting. Impressed by the complex riddle he recited it to his wife who could neither figure out the answer. When she finally gave up and asked for it, the Icelander said \'Well.. some NY cab driver of course!\'",
	"One of my friends works with a guy who keeps a shotgun by the from door \'just in case a nigger breaks in and tries to fuck my wife.\' \n\nI\'ve heard him say it with my own ears. \n\nBut the oddest thing is why would you keep it at the front door? If someone breaks in and B-lines for your wife\'s vagina, wouldn\'t you have to run all the way to the door and then all the way back? He could be a \'sprinter\' and finish in like 10 seconds and jump out the window. Hypothetically speaking.\n\nAlso his wife is the fattest and most beat woman I\'ve seen in my short life (23). There is no amount of money that would merit me exposing my penis in front of her.",
	"Here\'s an anecdote for you. I was leaving my (black) girlfriends apartment around 2AM one morning not far from the heart of the Watts area here in Los Angeles (I am white). My old beat up VW beetle (this was many years ago, har!) wouldn\'t start and it was very dark except for the street lamps. A young black man came walking up behind me on the sidewalk and asked if he could help push my VW to get it started. I greatfully accepted his offer and blissfully drove away waving my thanks to him. It didn\'t occur to me until I was well on my way home, that if I\'d had an ounce of courtesy I\'d have offered that black man a ride to wherever he was going. My failure to do so still haunts me to this day and I deeply regret my thoughtlessness. It\'s one of those things I wish were possible for me to go back in time and change.\n\nP.S. I would like to add this corollary to my previous comments. If there is anyone on this forum who thinks that racism doesn\'t exist anymore in America and you are white, try taking a walk in **any** American city while holding hands (as lovers do) with a black woman. You will find out from the dagger-like stares that you both get that racism is alive and well in the USA even if the racists among us won\'t admit it. Ironically enough, almost *all* of the disapproving stares come from white people, not from blacks - which is even more ironic if you can imagine the harassment a black-man holding hands with a white woman would get.\n\nIt even happens to a smaller degree with my Hispanic wife, but not nearly as much. ",
	"Having grown up in a probably typically racist area (mostly whites fearing everyone non-white), a lot of the lesser-racists just feared perceived cultural differences. Black people are \'loud,\' and \'rude,\' and \'obnoxious,\' according to them. They\'re fed on a diet of inner-city black people doing terrible things every night on the news. I noticed growing up that most of my white friends, and relatives, while not liking black people, had an ever-growing list of exceptions of black people they knew, who were \'okay.\' You\'d find out about these when a black person they knew was nearby when they spewed out some racist stuff, after which they\'d realize who was in the room, and append \'Oh, not you [whoever] - I didn\'t mean you. You\'re not like that. You\'re \'one of the good ones.\'\' After awhile, I realized the white folks were full of it, as every black person I\'d actually met, or dealt with was one of these few \'exceptions.\' I also think a lot of it is just simply being uncomfortable. I\'ve known plenty of white people who don\'t really have a problem with black people, but are still uncomfortable around them. What if they say something wrong, and sound racist, for example? I\'ve known a lot of very mildly racist folk who didn\'t like it about themselves. I\'d even put myself in that list to some degree. It\'s something I\'ve always had to work at, consciously, just like not eating so much pizza, and donuts. It\'s just a part of me that I don\'t like.",
	"Gave my dog crack once...\n\nNext thing I know he starts looting my stash.\n\nWhen the stash was gone he sold my TV to buy more crack.\n\nWhen everything of value was gone from my home he started breaking into other homes.\n\nIt all came to an end when in a drug crazed frenzy he broke into a home. The owner of the house caught my dog raping his dog. The home owner shot my dog then called the police.\n\nI was convicted of contributing to the delinquency of an animal and spent several years in prison.",
	"I scribble on post-it notes and tack them up on the side of my monitor. They fall off after a few days so I spread jelly on the back to re-energize the adhesive. Bees hum lazily at my ears all day, seeking out the source of the sweet odor. They take glue-tainted nectar back to their colonies. This may have some tenuous connection to the colony-collapse disorder phenomenon, but don\'t hold me to that.",
	"I was rolling a joint one night and my kitty looked interested.  So I stuck a bud in front of her to get a snif of it.  She hates everything that\'s not her food but she took a snif and bit the damned thing!  She\'s sitting there with this huge bud of pot in her mouth and I\'m trying to pull it out but that\'s just going to make her eat it.  I started to pry her mouth open and she let go of the whole thing.\n\nThen 20 minutes later she starts running from room to room, panicking.  It scared the hell out of me because what do I tell the vet if she really flips out?  But after a few minutes she calmed down and fell asleep beside me, none worse for wear.\n\nStupid thing.  She won\'t eat fresh steak and chicken but she\'ll eat this.\n\nLike this other time I had to give her these pills.  They were large and blue, covered in sone kind of membrane.  I\'m not jamming it down her throat so I cut the coating off, crush the pill and put it in food.  It worked.  So one night I\'m on the couch getting this thing ready.  I get the coating off it and set it on the couch beside me.  She sniffs it... and eats the damned thing whole!\n\nStupid kitties.\r\n",
	"I do it less now, but I used to set myself physical mini-challenges, whilst going about my business. If I succeeded I would earn the reward I was thinking about at the time.\n\nFor instance, if I can reach the top of the stairs before the door downstairs closes, then later, Mrs Eggs would put out/it\'d be chips for tea, that sort of thing.\n\nI\'d never measure my success, in case the \'magic\' disappeared...\n\nDaft, really.",
	"I\'ve worked very hard to have no responsibilities at all in my life, because any time I do have something to do on a particular date, and time, I can\'t accomplish anything at all until it\'s over. I have jury duty starting tomorrow. I\'ve known about it for 3 weeks. This is the most useless 3 weeks I\'ve ever experienced. It\'s like I\'ve been in the lobby waiting for my name to be called ever since I found the notice in my mailbox. My sleeping has been insane, and I\'ve had no motivation at all to even start projects. I have a mountain of things I\'ve wanted to accomplish, but my brain just won\'t let me while there\'s something \'big\' impending. This is why I live alone, never sign up for anything, nor schedule meetings, or appointments, or go to things like weddings. It\'s really crippling in some ways.",
	"I keep anything funny or interesting I think of or encounter in the drafts section for text messaging on my phone.\n\nWhen I\'m alone, I make noises that I like to think sound like a phat synthesizer. Constantly.\n\nI make ridiculous jokes most of the time at the cost of seeming weird.  For instance, at prom this year, on our way to a fancy restaurant, Never Gonna Give you Up came on the radio.  \n\n\'Did we just get Rick Roll\'d?!\' I yelled.\n\nMy friend laughed and I was happy someone got the joke.  Then I remembered that I had just told him about the rick roll a couple of weeks before.  \n\n",
	"I have no end of insane quirks. Here\'s another... I always, and I mean always, assume I\'m about to be attacked whenever I\'m not home, or in my office (edit: forgot - I always assume someone\'s about to break in, too, so scratch that). When walking to my car, there are muggers hiding behind every reasonably concealing object. I steer wide of anything like dumpsters, so no one can leap out and stick me with a knife, or grab me, and pull me down, cupping their hand over my mouth, drowning out my screams. This is patently insane, as I\'m 6\' tall, 260lbs, of fairly muscular build, and have a huge beard. People visibly walk in large arcs around me, including 4 guys in an alley once while I was walking to my car. I was certain we were going to have to throw down, but they split into pairs, and each pressed to either side of the alley, averting their eyes as they passed. At first, I assumed they were trying to flank me, and my eyes were darting everywhere looking for exits, weapons, and things I could throw them against to knock them out, or disable them. It turns out they were just intimidated by my giant, hairy self. I\'ve often wondered how many other gentle giant chickens there are out there.",
	"When I\'m eating a number of multicolored candies \u2014 jellybeans, Skittles, Starburst, etc. \u2014 I always eat them in a very defined color order. First purple, then red, then yellow, then orange, then green. I don\'t eat all of those colors in that order, though; rather, I\'ll eat one of each of those colors in a series, then go back and start the series again. The exception to that rule is that concerns the colors yellow, orange and green, as those are my, uh, favorite \'flavors,\' in descending order. Therefore, I will space out the series so that one of those colors is the last one that I will always eat.\n\nFor example, if I have two purple candies, four red candies, three yellow candies, three orange candies and two green candies, I will eat them in this order:\n\nPurple, Red, Yellow, Orange. Purple, Red, Yellow, Orange. Red, Yellow, Orange, Green. Red, Green.",
	"I used to stutter pretty bad when I was a kid. One day I discovered I could kind of sense when a stumbly word was coming up, and I would then switch it before I said it to keep my speech smooth. I use odd or flowery replacement words still as an adult to keep it under control, so I imagine I sound a little strange-- I don\'t stutter, and oddly my job is as a public speaker.\n\nMy second one: I remember moments. I\'ll pick a particular moment and do something memorable (nothing odd, just put my arms out, put my hand on my head, just so I can remember the situation easier) and save it in a different memory. My regular memories are all mishmashed goo, some out of order and nearly all fuzzy. My \'other\' memory (of these odd moments) consists of only 18 scenes and is completely recallable in order. It helps me feel connected with myself over time.",
	"I grew up always thinking that girls were super fragile, all the way into my first year of college, when I finally started really interacting with, and dating them. Until that time, I was super careful around them, so as not to injure them, or offend their delicate sensibilities.\n\nI was pleasantly shocked to find out how very tough many of them can be. One of them - whom I significantly outweighed - even managed to pick me up, and throw me into a wall while supposedly play-fighting. She actually hurt me, even though I pretended I was fine.",
	"Friends of friends stole about 8 boxes of cups, they claimed it was over 10,000 cups. They won no big prizes, but successfully invalidated the \'best buy bucks\' in Arizona in light of their theft.  They had over $3000 dollars in best buy bucks and upon driving to California to purchase an expensive item [plasma TV I think], were turned down at more than one location as no one had ever seen that many best buy bucks and refused to accept them.\n\nThey did, however, endure Supersize Me volumes of McDonalds as they won lots and lots of free food-- and since they were teenagers, they figured why not, and ended up spending all of the food coupons after a massive McDonalds binge lasting well over a month and, again according to my friend, eating McDonalds thrice daily.\n\nThis friend had a propensity for exaggeration, but he also had pictures of the cups and there was a veritable fuckload. I bought the story.",
	"Story time. I used to work for a paper in my town. I delivered 1,800 papers once a week. Well, I pretended too. My grandma and I would just toss the papers away since they were free and collect the money. McDonald\'s used to put those free stamps and \'stamp maps\' or whatever in every paper as an incentive so when we got that weeks papers, well, we opened ever single one and collected the glory. 3,600 stamps since there were two on every one. The highest thing we got was the Roller Coaster Tycoon game. Needless to say, however, I treated my friends to McDonald\'s every breakfast and lunch for about two to three weeks. \n\nMy friend did swear once to having Boardwalk. He was a liar though. ",
	"I\'ve had several weird dreams where family members were trying to kill me. One in particular, I was being chased by my younger brother and father. I could barely move. It was like my legs were made of lead. It was night in an old neighborhood where I grew up. \n\nAlso, once when I was younger (~13) I had a dream I was having sex with a girlfriend. I woke up midway through and was humping my pillow. That pillow never seemed the same after that.",
	"group of us were being run through a area populated with large machines with huge eyes trying to kill us in California, found an escape, one of the operators got killed by one of the machines, we used the stairs next to him to get to an exit, jumped down the tubes......came out the other side, all was dark, ran into some thorns, then the light came, jumped a fence, found out it was Hawaii, giant bird puked up another friend, and 2 blossomed out of pods.....went to find fishing poles and surf boards.... \n\nAnother weird one... \n\nWas riding around a city on some kind of self propelled inflatable mattress, looking at things and running from psycho cops that were trying to kill me for dressing different from the pinks that populated the city, I saw I lineup outside this big building that was a seriously high grade resturant/trance party, and got in the lineup..but the bouncer said I had to leave, as I was riding away on my mattress, Bob Sagat started hitting on me, and I let him pick me up because he could get me inside.. I woke up when he tried to kiss me after buying me a huge blue drink...\n\nWhat do you think..do I want bob sagat to pick me up? or is it a weirdly disconnected dream that would have lead to a hookup with the olson twins....i meen, I hope they would have been older then the full house days..but its a dream, and ya dont really get control unless ya go lucid..",
	"I\'m at a fancy lawn party with my parents and younger sister. It\'s a sunny, placid spring day and although not very exciting the party is pleasant. Suddenly, the host comes running outside, yelling about an emergency. He\'s just heard on the radio that a criminal organization is about to set off a nuclear bomb nearby! The party guests panic - my family and I dash to our car and start driving as fast as we can.\n\nThe atmosphere is tense, and we\'re making slow progress. The car radio has been delivering increasingly urgent warnings, becoming downright grim as we pass the neighborhood where I live. Then my dad slams on the brakes. \'We don\'t have enough time!\' He cries, \'We can\'t make it!\' I try to get him to start driving again, but he\'s frozen in terror and my pleas fall on deaf ears. Exasperated, I get out of the car and start running as fast as I can.\n\nI run until I\'m out of breath, then stop in front of a gas station to recover. I look behind me and my heart sinks. I realize that I\'ve barely made any progress; my efforts to escape are futile. Feeling stunned, and for lack of a better idea, I walk into the gas station and see a pinball machine. \'Might as well.\' I think, and insert a quarter. Just as I begin to play, I hear a powerful explosion.\n\nThe dream zooms out to third-person view of myself and I see a massive shockwave rip through the building, sending my body flying like a ragdoll. Then, in giant red letters, I see the words \'GAME OVER\'.\n\nThe dream zooms out again, and it\'s an arcade machine. Some random kid who was playing says \'Damn it!\' He bangs the machine, and leaves.",
	"I had a dream I was meditating on top of a remote mountain (as a kid, I never meditated-didn\'t know what it was really), and I experienced being whisked away at a post-luminal speed beyond our galaxy, the vast void of interstellar space, through and beyond a frenzy of other star systems.  So fast that the black, unfathomable expanse of space had a strange perception of a dim grid of grey and brown pattern of warped force lines, formed from the trace of light from stars.\n\nI was so scared and agoraphobic I was afraid I\'d never find the way back to earth, nor could I slow down.  I finally stopped next to a vast black object, like a cracked, spent ember universe of carbon.  I call it a dark star or comet.  It told me telepathically it was headed towards earth, to destroy it and everything else.  I was to relay the message and I was whisked back to the mountaintop.\n\nThis was a recurring dream.  There has been art, stories, and movies somewhat based on this theme, which makes me believe it\'s some kind of genome-stored impression with a meaning I don\'t fully understand.",
	"I record the dreams I remember in a notebook.  This entry is from a few years ago.  It certainly isn\'t the strangest, but one of my favorites:\n\nIn a childhood dream, I once visited a man who collected exotic animal\nbones.  He lined them up along the back of a soft wooden barn to bleach\nin the sun.  I played in the shadows they left on the grass.  A recent\ndream had me revisit him.  Things have changed--progressed rather,\nparallel with the time of my life.  Now he has a wonderful family and a\nnew passion: beautiful wax sculptures of vibrant colours.  They were\nmoulds he took of his father\'s body before he passed.  He handed them\nto me--arms, legs, and pieces of face.  The warmth of my hands made\nthem soft; they deformed in my hands.  The man did not seem to mind,\nbut it angered me.",
	"I killed 2 people in cold blood at a park, dropped the gun, changed my mind and picked it back up and spent the rest of the very long dream trying to escape some lady who had seen the incident and was chasing me.  The chase took me from europe to america and back, somehow all in that one dream.  In the end I was wrestling with her and pushed her out of a subway car as the doors closed..  I think thats about when I woke up.  In waking life I was visiting Madrid from California and had been psuedo-mugged (I didn\'t walk down the dark alley, but was shown a big knife from a distance and then forcibly begged from later..  cost me about $5) the evening prior to the dream.  Fun times. ",
	"I was hanging out in my brother\'s dorm room with him and his roommate.  I fell asleep on his bed for about a half hour and dreamed the following:\n\nFor some unknown reason my bro, his roommate, my roommate, and myself were in the woods in the middle of god only knows where sitting on the porch of an old log cabin.  suddenly everyone else decides to take the only vehicle at the log cabin and go back to my brother\'s roommate\'s house.  they thought it would be fun to leave me alone in the woods miles away from anything.  Well, after they all left I get up and walk through the woods (there were no roads.  wtf?)  a few miles into it I ran across an escalator that led up to a very big city.  for no reason at all, it was painfully obvious that I was in japan.  suddenly, midway up the escalator a train starts to climb up the base and my foot got stuck in the gaps of the escalator (now train track).  I managed to pull away, but my leg got cut off.  **scene transition** cut to 20,000 feet in the air.  I was flying in a rocket, but not a big rocket, just a tin can with a window.  I could here my brother\'s roommate talking through a radio, controlling my fate.  the rocket ran out of gas and I plunged into the ground.  the next thing I knew, I was back in the rocket flying again.  falling to my death wasn\'t enough to wake me up, so my mind does it again.  and again.  and again. all while this fuck is saying stuff about hitting updrafts and shit.\n\nthen my phone rang and I woke up.  turns out my bro\'s roommate way playing a flight simulator game and my mind was fucking with me.  I can\'t really explain the log cabin or the train, though.  one of the worst dreams ever.  the people say you can\'t feel pain in a dream just don\'t remember their dreams all that vividly.",
	"Two of my friends recently moved into their new place. They knew the neighbours in the apartment below were old and a bit miserable, but didn\'t think they\'d be this bad.\n\nSo anyway, after a Saturday night out drinking with said mates plus a few others, we go back to their place after the bars shut for a few more beers. This was the first time they\'d had a few people back in the night. Nobody\'s particularly loud, and in fact I don\'t even remember there being any music playing.\n\n3.30am rolled around, and me and a friend who\'s heading the same way decide to leave. As we go down the stairs, there\'s a bang on the glass part of the front door. Not a knocking, just a single thump. I ran down to see what it was, just in time to see the neighbour\'s apartment door close.\n\nI thought that was strange, since if he wanted to get someone\'s attention upstairs then all he need do is ring the doorbell. Plus, he definately must have heard me running down the stairs shouting \'hello?\' since he was only just inside by the time I opened the door.\n\nThe next day, I caught up with my mates who\'s apartment I was in the night before. He tells me that the old guy had rang my friends PARENTS at 4 in the morning, rather than ask us to shutup.\n\nHis parents, terrified after picking up the phone at 4am on a sunday morning to be asked \'are you the parents of [their son]\', said to him \'what\'s the hell\'s this got to do with us?\' - to which the old guy said \'well they\'re keeping me up, so I\'m gonna keep you up\'.\n\nBut wait - how did Old Man know my friend\'s parent\'s number? He doesn\'t know them at all. Turns out he had held on to some of my mate\'s mail that had been forwarded WEEKS ago from his parent\'s house, and looked up the surname and address in the phone book. Seriously, some people should drop dead after they retire - they really have nothing better to do with their lives.",
	"I was a non-traditional student. Dropped out in the 8th grade. Got my GED at 19, went to community college for a couple years, and eventually went to a state university for 3 years and got a degree in Philosophy (yeah, yeah). Was it necessary? Nah. I was a self learner and ambitious before college. I had initiative, and had my own business when I was 12. Didn\'t get rich or anything, but made about $300 a month selling BBS door games. Not a living, but proof you can do things without a degree.\n\nWhat\'s important about college, I think, is the 1) immersion in an environment of curiosity and debate and 2) learning the rigor of solving tasks and problems yourself. I\'m a believer in the tradition of the liberal arts. Rhetoric, science, logic, and math are essential skills everyone should have when they are walking around on this rock. Immersing yourself in a culture where those things are important help to assign a value-- isntead of a hobby explored by yourself, they are important life issues to be shared with others.\n\nIf you already have that consciousness, if those things are already important to you and you are able to share and debate them with others, then college becomes less important.",
	"Last night, I got completely plastered at a club and started pissing on some girls car. (Yeeah, rejection is a bitch) Well, a cop rolled up, so I took off running. Except my pants were at my ankle. I hit my face and it started bleeding.\n\nThen the cop arrests me, gives me a breathalyzer (I blow a .22. I am proud of that.) Puts me in cuffs, and throws me in the back of the car. I pass out, and then wake up and vomit all over the metal cage.\n\nI get booked and spend a night in the drunk tank. I met some pretty interesting people, but I don\'t remember names or faces. Finally, I get out and sober up. My charge? Public urination, only a misdimenor. ",
	"I was entering my residence once when this drugged up guy attacked me.  I couldn\'t knock him out, and I couldn\'t get the door closed because I had no traction on the floor (in socks), so I ended up fighting this guy off for a good 20 mins before the police finally showed up.  Fortunately he was too fucked to be able to land any decent punches, but after 20 mins of trying to knock him out he was in a bad way.  The police came, saw me with just a couple scratches, saw him covered in blood, all over the floor and walls too, and decided they had to arrest me too.  Took me 24 hours in Manhattan\'s system to get back home!  I heard in court later that he had 3 broken fingers, broken jaw, broken nose, fractured skull, fractured wrist, and 14 stitches.  Fucker deserved every last one.  I was charged with a felony assault (apparently a door is a weapon, which is how his fingers and wrist got injured), but they eventually dropped all charges.",
	"I was drinking with my friends at a college town bar.  One of my friends got too drunk and started acting a fool, so I knocked his ass out.  He regained consciousness as the bouncers were hauling him up, and holding me in a choke hold.  He said he didn\'t want to press charges, but they sent an ambulence for him anyway.  The ambulence came, along with cop cars.  He was taken to the hospital, I dodged out the back door near the bathrooms.  Things calmed down as I hid in the bushes, finishing my double Jack n Coke.  Eventually, I entered the bar area again.  There were half-emptied beers left on random tables and counter tops (outside patio, damn smokers) which I promptly drank as I walked back into the bar.  The cops had left.  As I approached the bar to order another drink, the bouncers swarmed.  They beat the fuck outta me.  Then, they carried me outside the front entrance.  Where, yeah, there were cops.  The cops told me to walk my ass home, I\'d had enough to drink, and so I began walking home.  But, fuck that!  It\'s time to call 911 and teach those bastards a lesson.  I round the corner of the building, continue around back, and dial it up on my phone.  \'Yes, hello?  There\'s a bomb in *name of bar*, I think you should evacuate it immediately.\'  Thank you, the responder mentioned and I hung up.  Take that, shit-eaters.\n\nYeah, no bomb, of course.  So, I walk back around front and try to get back in.  They don\'t let me in.  They grab me, and shit, the cops are still there.  The cops grab me, cuff me, and throw me in the car.  \n\nI spent the night in jail, got off on bond for now.\n\nI\'ll probably be in jail for a while after my trial.  \n\nI thought I\'d share it here with all of you.  My only real concern is that I was the lead programming project and I don\'t know what they\'ll do without me.",
	"When I was in College, it was insanely easy to get drinks at bars in Columbus, OH (even with a giant \'X\' on your hand.)\n\nThe cops came in every night and grabbed a few of the idiots that were standing by the front door and not quick enough to put their drink down without being seen. My strategy was to always hang at the very back of the bar, and always with a table nearby to set my drink down on. That worked exceptionally well until one day some girl asked me \'so, when do you turn 21 anyway?\' rather loudly. Apparently, there was an undercover cop in there because not even 5 minutes after her comment, the uniformed cops came for me, and very specifically for me. \n\nSo the paddy wagon was around the corner from the bar, and they threw me in the back while they wrote me a ticket. More than a few people I knew stopped to point  and make faces while I was in there, as was the ritual at the time. $350 fine and community service digging holes for tree saplings with a bunch of other students and some actual inmates in prison garb. NOT fun.",
	"\'When I was 17....\'  I was sitting bitch in my friends car.  There was weed and hash being passed around.  The driver got smart and rolled down his window right as a cop drove past.  We got pulled in the parking lot of a Lil\' Cricket.  I just remember laughing hysterically at the blue blinky lights in his rear view.\n\nWe got taken further downtown than we already were.  I claimed suicidal (I had a bad day two weeks prior), and it wasn\'t until I was being transferred to psych that they found my quarter...bastards.\n\nI was bailed out by my parents the next morning.  The best part was the bail bondsman drove up as we were leaving and I got a big lecture about how long I would have had to stay if I had waited for him.  Of all the things to think of to tell me at that moment.\n\nThe judge was nice and listened to my dad\'s unemployment story and my mom\'s \'struggling-between-jobs-to-feed-us-all\' (My BK earnings exceeded both of theirs put together) and decided to dismiss the charges.\n\nI\'ve come a long way since then.  Now I always sit shotgun.",
	"Here\'s a story I shared about two months ago, concerning tasering....\n\n\'I was tased in a police station. I refused to \'blow\' in a breathalyzer so they tased me for not complying. It was a gun taser, it shot two prongs into my chest (I still have the scars). If they would have threatened to use it, I probably would have complied but they just shot me with the damn thing. The look on the face of the cop who tased me was the same look a 12 year old has when he burns ants through a magnifying glass. I think that\'s the most disturbing memory I have of the incident. I was pretty hammered at the time but I do remember buckling over and pulling the wires (attached to the prongs) out of my chest. It was not anything I would voluntarily do again.\'\n\nThis was the result of drinking and driving.   Been sober since this incident (two years).",
	"I used to drive limousines for this huge pot dealer...I mean huge, he didn\'t deal in small time crap, it was all pounds.  Well, one night I went out to pick up the limo for a gig and I seen a county sheriffs car parked in his driveway. I almost kept going but I had slowed down for the turn and the cops would have stopped me anyways. As soon as I did pull in all I seen was cops...everywhere...they were all suited up in their \'Rambo\' outfits...shotgun belts..the whole nine yards. A few of them swarmed my truck, making me get out and questioning me..they checked my truck inside and out..looking for hidden compartments...one cop kept fooling with the passenger side airbag and I was waiting for it  go off.  Anyways, they pulled me into the limo office and questioned the shit out of me..the good cop/bad cop scenario.  I was only there to pick up the limo and I had my limo garb on so they couldn\'t accuse me of being in league with my boss (although I did know a lot about what went on) and they finally let me go. I had to call my people that I was supposed to drive that night because the coppers wouldn\'t let me take a limo.  He ended up going to jail, paid 10k to run a trial and ended up moving away.  The cops never did find anything (he wasn\'t stupid, he never kept his shit at his house), but a roach in an ashtray. ",
	"The front of my building is glass and there are two separate glass door entrances, they pay someone to open the doors for us as we enter / leave and take it pretty serious. As I get off the elevator, he\'s already spotting which door I\'m heading to, and starts walking down there, I immediately tilt my head slightly to the other door and he switches directions, I do this about 2-3 times before I finally get to the door and scoff, \'uh thanks\' when I beat him to it.",
	"I was at a friend\'s surprise party this spring. The party was on April Fools Day and it was a lesbian themed party. My friend is a straight male. \n\nSo, the surprise goes off awesomely and games and tokes start everywhere. \n\nAt one point I was sitting on the couch by the front door with a friend talking metal vs blues and this tall metalhead in a gorilla mask walks up and starts talking to my friend. Apparently they now each other through their jobs. I meet Gorilla Man, shake his hand and went to get some cake. \n\nLater still, I see Gorilla Man sans mask. Fucking hell he was hot. Tall, Ginger metalhead in big black boots, bullet belt and is covered in awesome Satanic and death tattoos. \n\nI had to talk to this man.\n\nWhat followed was possibly the best conversation I have ever had with a stranger. What clinched it for me was his name. I\'m not going to tell you all what his name is, for obvious reasons. But, let\'s just say that it was extremely unique and suited him like nothing I had ever seen.\n\nWe \'dated\' for nine month and then it ended suddenly when things got super serious emotionally. Neither of us are capable of that kind of emotion at this point. \n\nStill, I think of our meeting as one of the best things that has ever happened to me.",
	"I had my wedding band resized at around 3 months. Why not the engagement ring as well, you ask? Well, because I didn\'t put it on and then have it get stuck and have to be cut off by (a hunky, charming, crew of five) firemen. We had it resized as it was repaired, and I wore it by itself until the engagement ring fit again at about 6-9 months. Luckily since that one is worn on the outside, it holds the now-loose wedding band on. \n\nBe patient, and for the love of all that is good, do not put them on if you think you might have a hard time getting them off.",
	"My dad was Bucky when he went to school here.Many family members attended and I have been raised as a Badger fan my whole life.  I tried to get into school here but got waitlisted.  Went to undergrad a couple hours away instead.  Graduated and got a job in Madison about a mile from the stadium.  Going to school for my masters online right now through the University of Florida but being so far away, I\'m not really a fan.  ",
	"They were still friends for about eight years after they divorced, but they ended up falling out due to child support issues and my dad fleeing the country.\n\nMy mom didn\'t marry again afterwards, my dad ended up getting married twice afterwards.\n\nThey probably had some feelings for each other in high school, but they both were already in relationships with other people during high school.\n\nI used to think it would have been really cool if they were to get back together, because I wanted to have that perfect family unit. But now as an adult, I would only want them to get back together if they were truly in love, which I don\'t ever see happening.",
	"Whenever I\'m walking in a crowded hallway I brush hands with the people next to me. It\'s even better when people are just a little bit ahead of me because then I can reach up a bit and get their palms. They usually freak out and jerk their hands away. \n\nI also like finding the radio station that the car next to me is listening to so that I can roll down the windows and turn up the volume really loud. Eye contact with strangers is fun. ",
	"I was living in a small city in Australia and I had some friends around at my rental property. long story short my best friend (last to leave) didnt put his cigarette out properly and it blew onto a couch I had on the patio. set the whole place on fire and the house had to get torn down.\n\nso I figured I didnt have any stuff to move so now is the time to do it. I said goodbyes and moved to melbourne (it is like a 4 hour plane trip so I wouldnt be seeing a lot of people again). any way melbourne was really cool, met this girl, it was great. I was living with my aunt and uncle for a while so I decided to move in with my girlfriend, she was living with her best friend and her best friends mother. \n\nthen, maybe a year after I moved, my best friend finally saved enough money for a visit. he stayed with us and he hit it off with my girlfriends best friend. after another visit 2 months later, she moved up to my old home town to be with him. that was 4 years ago.",
	"Teaching history correctly requires context, I would be surprised if putting 13 year olds in blackface would give them any appreciation for the hardships of slavery or even the racial hangover this country seems to have. \n\nUnless you were to drop them into the middle of the inner city and pick them up a few hours later. You might lose a couple of kids but the rest would have learnt one hell of a lesson.\n\nIn my opinion though, the biggest problem with racism today is the amount of people not understanding that people might find things offensive.",
	"One time in high school I sharpened a pencil and carved \'die\' in my arm during math class cause I was bored. A large black girl that was bussed into our school from the inner city asked me about it, and then reported it to the administration. They sat me down and talked to me about it, and I told them I did it out of boredom. All in all I think I went to a fine high school. It ended with that, and I stopped carving stuff into my arms, even if I was bored.",
	"I ignore judgment. I am who I am, and if someone doesn\'t like that they can suck my non-existent dick. The only person who\'s affected me with their judgment so far, though, is my father, but even though he doesn\'t support my decision, he also wants to see me happy and successful, and loves me as his flesh and blood.\n\nPeople dealing with harsh judgment (about anything, not just gender identity) need to realize that the people that matter will accept them no matter what the person throws at them.",
	"Your emotions about it will become tempered over time.  But, you will never fully trust the other person again.  You will always be suspicious of that person - even if it is only in the back of your head and you never say or do anything.  You will have to remind yourself - *that* is in the past - I must move on.  But, that little voice in your head keeps talking...  Ultimately, you have to decide if it is worth it - but, it never goes away.\n\nEven with someone new, when you have no reason to distrust, you will think it - and the logical you will tell you that the new person has done nothing to deserve this - and therefore you will not likely say or do anything.\n\n*Innocence lost can never be recovered...  We were all innocent, once..."
];

var creditJSON = '[\
    {"author":"christianjb","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"righttoresist","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"shacamin","subeddit":"AskReddit"},\
	{"author":"chicomathmom","subeddit":"AskReddit"},\
	{"author":"chicomathmom","subeddit":"AskReddit"},\
	{"author":"MrKlaatu","subeddit":"AskReddit"},\
	{"author":"oalsaker","subeddit":"AskReddit"},\
	{"author":"you_do_realize","subeddit":"AskReddit"},\
	{"author":"WaterDragon","subeddit":"AskReddit"},\
	{"author":"BobGaffney","subeddit":"AskReddit"},\
	{"author":"gfixler"},\
	{"author":"Derferman","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"rmuser","subeddit":"AskReddit"},\
	{"author":"Starcrusher","subeddit":"AskReddit"},\
	{"author":"eggnogdog","subeddit":"AskReddit"},\
	{"author":"captain_republican","subeddit":"AskReddit"},\
	{"author":"mrp","subeddit":"AskReddit"},\
	{"author":"tuoder","subeddit":"AskReddit"},\
	{"author":"Xeiliex","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"begone","subeddit":"AskReddit"},\
	{"author":"slyguy183","subeddit":"AskReddit"},\
	{"author":"xoctor","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"rmuser"},\
	{"author":"kounavi","subeddit":"AskReddit"},\
	{"author":"boesman","subeddit":"AskReddit"},\
	{"author":"multi_touch","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"Kardlonoc","subeddit":"AskReddit"},\
	{"author":"topsul","subeddit":"AskReddit"},\
	{"author":"shacamin","subeddit":"AskReddit"},\
	{"author":"ralphwiggum","subeddit":"AskReddit"},\
	{"author":"eks","subeddit":"AskReddit"},\
	{"author":"so_sleepy","subeddit":"AskReddit"},\
	{"author":"NotSoHotPink","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"rosshettel","subeddit":"AskReddit"},\
	{"author":"nemof","subeddit":"AskReddit"},\
	{"author":"starbork","subeddit":"AskReddit"},\
	{"author":"jjrs","subeddit":"AskReddit"},\
	{"author":"hahamoviequote","subeddit":"AskReddit"},\
	{"author":"artesios","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"davega7","subeddit":"AskReddit"},\
	{"author":"arnar","subeddit":"AskReddit"},\
	{"author":"BlueBeard","subeddit":"AskReddit"},\
	{"author":"RKBA","subeddit":"AskReddit"},\
	{"author":"gfixler","subeddit":"AskReddit"},\
	{"author":"Satanscock","subeddit":"AskReddit"},\
	{"author":"Farsay","subeddit":"AskReddit"},\
	{"author":"turkourjurbs","subeddit":"AskReddit"},\
	{"author":"MisterEggs","subeddit":"AskReddit"},\
	{"author":"gfixler","subeddit":"AskReddit"},\
	{"author":"eggnogdog","subeddit":"AskReddit"},\
	{"author":"gfixler","subeddit":"AskReddit"},\
	{"author":"metal_falsetto","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"gfixler","subeddit":"AskReddit"},\
	{"author":"eggnogdog","subeddit":"AskReddit"},\
	{"author":"tridentgum","subeddit":"AskReddit"},\
	{"author":"Qubed","subeddit":"AskReddit"},\
	{"author":"docid","subeddit":"AskReddit"},\
	{"author":"gimeit","subeddit":"AskReddit"},\
	{"author":"mchrisneglia","subeddit":"AskReddit"},\
	{"author":"xxeyes","subeddit":"AskReddit"},\
	{"author":"mdeckert","subeddit":"AskReddit"},\
	{"author":"0_o","subeddit":"AskReddit"},\
	{"author":"wjw75","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"goodbyeworld","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"DrunkenAsshole","subeddit":"AskReddit"},\
	{"author":"sfgeek","subeddit":"AskReddit"},\
	{"author":"LabThug","subeddit":"AskReddit"},\
	{"author":"Noche","subeddit":"AskReddit"},\
	{"author":"Noche","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"AskReddit"},\
	{"author":"yellin","subeddit":"Mommit"},\
	{"author":"T1K1","subeddit":"CFB"},\
	{"author":"Fckusernames","subeddit":"IAmA"},\
	{"author":"nsoysauce","subeddit":"AskReddit"},\
	{"author":"samthedeer","subeddit":"AskReddit"},\
	{"author":"[deleted]","subeddit":"WTF"},\
	{"author":"[deleted]","subeddit":"funny"},\
	{"author":"stokesthekid","subeddit":"IAmA"},\
	{"author":"bigroblee","subeddit":"funny"},\
	{"author":"SuperGRB","subeddit":"relationships"}\
]'

var TITLE = 'PHRADMUS';
var SUBTITLE = 'A Book of Myths';
var SUBTEXT = 'Written and collected by \n Guy de Bree';
var edgeBuff = 38;

function pad(n, width, z) {
  z = z || '0';
  n = n + '';
  return n.length >= width ? n : new Array(width - n.length + 1).join(z) + n;
}

function drawChapterPage(pgNo, chNo, story){
	b.addPage();

	b.textFont('Courier','Bold');
	b.textSize(36);
	
	b.text(chNo + "" ,0,edgeBuff*2,b.width,100);

	b.textFont('Helvetica');
	b.textSize(10);
	b.text(pgNo + "", 0, b.height - edgeBuff  - 20, b.width, b.height - edgeBuff);

	b.textFont('Helvetica','Italic');
	b.textSize(12);
	b.textAlign(Justification.LEFT_ALIGN);
	b.text(story + "", edgeBuff, 150, b.width - (edgeBuff * 2), b.height - 250);
}

function drawNormalPage(pgNo, imgNo, story){
	b.addPage();
	var imgPath = new File('~/Pictures/phradmus_imgs/' + pad(imgNo, 9) + '.png');
	b.image(imgPath, b.width/2 - 50, 80, 100, 100); 

	b.textFont('Helvetica');
	b.textSize(12);
	b.textAlign(Justification.LEFT_ALIGN);
	b.text(story + "", edgeBuff, 200, b.width - (edgeBuff * 2), b.height - 300);

	b.textFont('Helvetica');
	b.textSize(10);
	b.textAlign(Justification.CENTER_ALIGN);
	b.text(pgNo + "", 0, b.height - edgeBuff  - 20, b.width, b.height - edgeBuff);

}

function setup(){

	var creditJSONData = b.JSON.decode( creditJSON );
	var authorSet = {};
	var authorArr = []

	b.println("preparing to gather " + creditJSONData.length + " authors ");

	for(var i = 0; i < creditJSONData.length; i++){
		var s = creditJSONData[i].author;
		if(!(s in authorSet)){
			authorSet[s] = s;
			authorArr.push(s);
		}
	}

	b.println(authorArr.length + " unique authors ");
	
	var authorLists = ["","","",""];

	for(var i = 0; i < authorArr.length; i++){
		authorLists[i%4] = authorLists[i%4] + authorArr[i] + "\n";
	
	}


	var div = redditStoryStrings.length / myStoryStrings.length - 1;

	b.println( "Hello World!" );

	b.textFont('Arial','Bold');
	b.textSize(90);
	b.textAlign(Justification.CENTER_ALIGN);
	b.text(TITLE,0,b.height/5,b.width,100);

	b.textFont('Helvetica');
	b.textSize(40);
  	b.text(SUBTITLE,0, b.height/3, b.width, 50);

  	b.textSize(26);
  	b.text(SUBTEXT, 0, b.height/3 * 2 , b.width, 100);

  	b.addPage();
  	b.addPage();

  	b.textFont('Helvetica','Italic');
	b.textSize(12);
	b.textAlign(Justification.CENTER_ALIGN);
	b.text("For any poor soul unfortunate enough to be immortal.\nIf any exist.", 0, 150, b.width, b.height - 100);

	//drawChapterPage(1, 1, myStoryStrings[0]);
	//drawNormalPage(2,1,redditStoryStrings[0]);

	var pageCount = 1;
	var imgCount = 1;
	var currRedditStory = 0;

	for(var i = 0; i < myStoryStrings.length; i++){

		drawChapterPage(pageCount, i + 1, myStoryStrings[i]);

		pageCount += 1;

		for(var j = 0; j < div; j++){
			drawNormalPage(pageCount, imgCount, redditStoryStrings[currRedditStory]);
			currRedditStory += 1;
			pageCount += 1;
			imgCount += 1;
		}

	}

	while(currRedditStory < redditStoryStrings.length){
		b.println(redditStoryStrings[currRedditStory] + " | " + redditStoryStrings[currRedditStory].length);
		if (redditStoryStrings[currRedditStory] == null) {break;}
		drawNormalPage(pageCount, imgCount, redditStoryStrings[currRedditStory]);
		currRedditStory += 1;
		pageCount += 1;
		imgCount += 1;
	}

	b.addPage();

	b.textFont('Helvetica');
	b.textSize(14);
	b.textAlign(Justification.LEFT_ALIGN);
	b.text("Stories from the following Reddit users:", 30, 75, b.width - 30, 20);


	b.textSize(12);
	var buffer = 32;
	var colWidth = (b.width - buffer * 5)/4
	for(var i = 0; i < 4; i++){
		b.println("col " + i + " length is " + authorLists[i].length);
		b.text(authorLists[i], buffer*(i + 1) + colWidth*i, 100, colWidth, b.height - 150);
	}


}

b.go();